# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 00:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import satchless.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('nouveau', 'Processing'), ('annuler', 'Cancelled'), ('shipped', 'Shipped')], default='GroupStatus.NEW', max_length=30, protected=True)),
                ('shipping_method_name', models.CharField(blank=True, default=None, editable=False, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=(models.Model, satchless.item.ItemSet),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('ouvert', 'Open'), ('fermer', 'Closed')], max_length=32)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.Order')),
            ],
            options={
                'ordering': ('date',),
                'db_table': 'orderhistory',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, null=True)),
                ('product_sku', models.CharField(max_length=32, null=True)),
                ('unit_price_net', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price_gross', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('delivery_group', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.DeliveryGroup')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etrans.Product')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etrans.Stock')),
            ],
            options={
                'db_table': 'orderline',
            },
            bases=(models.Model, satchless.item.ItemLine),
        ),
        migrations.AddField(
            model_name='deliverygroup',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='orders.Order'),
        ),
    ]
